image: gcc

stages:
  - build
  
build:
  stage: build
  
  before_script:
    - apt update && apt -y install make autoconf
    
  script:
    - g++ *.cpp -o bin/test.dll
  
  artifacts:
    paths:
      - bin/
